
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://abfrzrhzvfjwwslwawko.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFiZnJ6cmh6dmZqd3dzbHdhd2tvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkwMjgxNTksImV4cCI6MjA1NDYwNDE1OX0.pKIzHm2eQac33whKAhzSSWBtRRTgCrTpuKzETjCjvsA";

// Get admin email from localStorage if it exists
const adminEmail = typeof window !== 'undefined' ? localStorage.getItem('adminEmail') : null;

// Create Supabase client with global headers
export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    global: {
      headers: {
        'admin-email': adminEmail || 'no-email'
      }
    }
  }
);

// Update headers when admin status changes
export const updateSupabaseHeaders = () => {
  const currentAdminEmail = localStorage.getItem('adminEmail');
  supabase.rest.headers['admin-email'] = currentAdminEmail || 'no-email';
};
