
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://abfrzrhzvfjwwslwawko.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFiZnJ6cmh6dmZqd3dzbHdhd2tvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkwMjgxNTksImV4cCI6MjA1NDYwNDE1OX0.pKIzHm2eQac33whKAhzSSWBtRRTgCrTpuKzETjCjvsA";

// Create a single instance of the Supabase client
export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    global: {
      headers: {
        'admin-email': 'no-email' // Default header
      }
    }
  }
);

// Update headers when admin status changes
export const updateSupabaseHeaders = () => {
  const adminEmail = localStorage.getItem('adminEmail');
  
  // Update the client's headers using setHeaders method
  supabase.auth.setSession({
    access_token: '',
    refresh_token: ''
  }).then(() => {
    if (adminEmail) {
      supabase.auth.setSession({
        access_token: '',
        refresh_token: '',
      }, {
        headers: { 'admin-email': adminEmail }
      });
    } else {
      supabase.auth.setSession({
        access_token: '',
        refresh_token: '',
      }, {
        headers: { 'admin-email': 'no-email' }
      });
    }
  });
};

// Function to check if user is admin
export const checkAdminStatus = async () => {
  const adminEmail = localStorage.getItem('adminEmail');
  if (!adminEmail) return false;

  try {
    const { data, error } = await supabase
      .from('admins')
      .select('email')
      .eq('email', adminEmail)
      .single();

    if (error) throw error;
    return !!data;
  } catch (error) {
    console.error('Admin check error:', error);
    return false;
  }
};
